### ISSUE TITLE
"Huh?" -day 103

### ISSUE THREAD

**Issue by Forstio** [6zs/xordle#1]
So uh, basically for day 103 i have down "BLANK" and the letters are all green... but right next to it a word says "huh?" what does this mean?

![image](https://user-images.githubusercontent.com/103157162/162100986-5cd57da0-75f0-4d9e-a0c0-69d7ad7ddfbb.png)

**Comment by CuddlyPenguin** [comment]
This means that the "B", "L", "A", "N", and "K" are all in the correct spots for ONE of the two words. However, the "huh?" means that they aren't all in the same word. For example (ignoring the black "I" at the top), one of the words could be BLINK, and the second word would have an A in the center. But BLANK is neither of the two words.

In the following image, even though PUKER was all green, the correct word was POKER, and the "U" was in the correct spot for the second word.

<img width="293" alt="Screen Shot 2022-04-06 at 6 30 45 PM" src="https://user-images.githubusercontent.com/100059844/162102224-afe9a051-ca48-4ac3-92e5-c74c4de4dd2e.png">
