### ISSUE TITLE
Scoring

### ISSUE THREAD

**Issue by wrperin** [6zs/xordle#2]
Hello, fun game! I'm confused by the scoring. The rules state I get 9 tries to guess both words; however, in the stats area the guesses include the "bonus" try to equal 10 when it's really the 9th guess.
xordle # 109 10/9
⬛🟨⬛🟩🟩 provided random clue
⬛⬛🟩🟩⬛
⬛🟨🟩🟩🟨
🟨🟩🟩⬛🟩
🟩🟩🟩🟨🟩
🟨🟩🟩🟩🟩
⬛🟩🟩🟩🟩
⬛🟩🟩🟩🟩
🟩🟩🟩🟩🟩
🟩🟩🟩🟩🟩 bonus? This is my 9th guess
https://xordle.xyz/
![image](https://user-images.githubusercontent.com/37532683/162579868-8e865f97-ba06-4a81-8f77-0fcab3d24e64.png)

**Comment by CuddlyPenguin** [comment]
Hello! So from what I can tell, the random provided clue counts as one of the guesses, so really we have 8 chosen guesses and 1 given guess. I'm very confused as to where you got the tenth slot from, all of my boards only have a max of nine slots total, one of them already being filled. There is also no 10 in my stats page... When did the game give this "bonus"?

My Stats Page (there is no 10 slot):
<img width="367" alt="Screen Shot 2022-04-11 at 5 34 46 PM" src="https://user-images.githubusercontent.com/100059844/162855139-ea74c1e9-084a-469b-bf81-dc2870d53593.png">

**Comment by 6zs** [comment]
Yep, it counts the given guess as one of your guesses. Maybe that's not communicated well. 

You get a 10th slot if you get one of the words on the very last try. That way as long as you're still typing, you can still win :)
