### ISSUE TITLE
Words changed?

### ISSUE THREAD

**Issue by numbersarereal** [6zs/xordle#6]
I started day 34 with the given word WEIRD and I started to make my guesses. I got down to one word correct (SWARM) and then my dad texted me and I realised that we were playing different games. I assumed he was playing unlimited but when I refreshed my browser all my colours changed to reflect the (presumably correct) day 34. It still said WEIRD at the top but the letters were coloured as if the correct words were LUNAR and KITTY (i.e. my previously all green SWARM went to a yellow A and R and despite being accepted as correct, the keyboard at the bottom shows KITTY as all wrong).

![Screenshot_20220504-004820](https://user-images.githubusercontent.com/104873678/166600190-c2700ff8-e381-4743-89b5-456c79f9b857.png)

![Screenshot_20220504-005021](https://user-images.githubusercontent.com/104873678/166603322-e932031d-dda3-4b52-a189-30b1c95a9ee2.png)

Literally no clue what this means!

**Comment by 6zs** [comment]
dang, that's unfortunate. i did change today's puzzle a few days ago; it means the browser didn't download an update until you refreshed and so was playing on the would-be words. i believe i've fixed it so the game will always check for an update before making a new daily puzzle
